### DISCUSSION TITLE
Task/Job Urgency

### DISCUSSION THREAD

**Discussion by dagraham** [dagraham/tklr-dgraham#9] [General]
While tasks are created directly and jobs are created indirectly as @j components of a task, both have similar entries in the in the data store as records in the Urgency table and each is assigned a floating point urgency score in this table. This score depends both upon the characteristics of the task/job and user "urgency" configuration settings stored in the "urgency" section of "config.toml".  (The use of "toml" (tom's obvious markup language) is rapidly becoming the default for python.)  The following are some tentative default settings for the urgency section of this file together with a suggestion of associated contribution to urgency.  

The key issue is that a characteristic of a task/job will only have an effect on its urgency if there is a corresponding urgency setting in config.toml.  The issue now is whether there are any omissions?

## active

```toml
# At most one task/job can be designated the active task at any point in time.
# Is this task currently the active task? If so, add active_value to urgency.
active_value = 20.0
# urgency += active_value if active else 0.0
```

## age

```toml
# How long since the task was created. The greater the age, the greater the urgency.
age_daily = 0.2
# urgency += (now - created).days() * age_daily
```

## blocking

```toml
# Is this
# 1) a job that is available (unfinished and without unfinished prerequisites) and
# 2) a prerequisite for another unfinished job?
# If so, add blocking_value for each job for which this job is a prerequisite
blocking_value = 1.0
# urgency += blocking_value * blocking
```

## description

```toml
# Does this task/job have a description? If so add description_value to urgency.
description_value = 2.0
# urgency += description_value
```

## extent

```toml
# Does the task/job have an extent? If so, add urgency at this rate
# per hour of extent.
extent_hourly = 0.25
# urgency += extent.seconds()/3600.0 * extent_hourly
```

## priority

```toml
# Does this task have a priority setting? If so apply to the task itself
# if there are no jobs, otherwise to each job.
priority.next = 15.0
priority.high = 6.0
priority.medium = 2.0
priority.low = -2.0
priority.someday = -6.0
# urgency += priority['priority']
```

## tags

```toml
# Add tag_value to urgency for each assigned tag
tag_value = 1.0
# urgency += tag_value
```

## current

```toml
# How recently has the record been "touched"? The more recent, the greater the urgency.
# The contribution to urgency is positive over the interval from now == touched
# until now == touched + current_interval. Note that now >= touched is always true.
current_interval = "7d"
# the maximum contribution to urgency when `now == touched`
current_value = 4.0
# urgency += max(0, current_value(1 - (now - touched)/current_interval))
```

## due

```toml
# How soon is the due (scheduled) date? Or how long ago? The sooner or the
# longer ago, the greater the urgency.
# How long before scheduled to start adding to urgency;
due_interval = "7d"
# the maximum contribution to urgency when now = due
due_value = 16.0
# The ratio, due_value/due_interval, gives the rate at which urgency increases
# before scheduled. The rate after scheduled, when the task is past due, is
# obtained  by multiplying this rate by
past_due_adjustment = 0.5
# urgency +=  max(0, due_value(1 - max(scheduled - now, 0) * 1/due_interval + max(now - scheduled) * past_due_adjustment/due_interval))
```
